[package]
name = "macroquad_sprites"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3" 

rglk_graphics = { path = "../rglk_graphics" }
rglk_math = { path = "../rglk_math" }